### ISSUE TITLE
Android Studio and react native bundler method conflicts

### ISSUE THREAD

**Issue by iamchathu** [brodybits/create-react-native-module#108]
I have added more information about the question in [Stackoverflow](https://stackoverflow.com/questions/57834464/react-native-android-module-conflicting-with-andorid-studio-and-react-native-bui)

**Comment by iamchathu** [comment]
Seems you are not using `node-modules` react native version inside the generated Android project.

**Comment by brodybits** [comment]
> I have added more information about the question in [Stackoverflow](https://stackoverflow.com/questions/57834464/react-native-android-module-conflicting-with-andorid-studio-and-react-native-bui)

I just upvoted the question and existing answer. I cannot promise when I will get a chance to parse what may be going on and try to reproduce the issue.

> Seems you are not using `node-modules` react native version inside the generated Android project.

Can you or someone else explain this in some easier terms?

Help from the user community would be much appreciated.

**Comment by brodybits** [comment]
Is this covered by #120 or is it something different?

**Comment by brodybits** [comment]
I am closing this since I really do not follow what is going on and have not seen response to my followup questions.

**Comment by iamchathu** [comment]
@brodybits For now I generated new project and migrated my old project to new version and it's works now.

**Comment by brodybits** [comment]
Thanks for the confirmation.
