### ISSUE TITLE
[...] @brodybits involvement with tvOS support

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#127]
This information in response to a question I received by email:

tvOS was contributed in PR #91, and I have tested it with and without using the `--view` option for custom view (see discussion in #95 for more details)

I have also raised react-native-community/react-native-tvos#15 to get an idea of the amount users, developers, and commercial interest with tvOS may be out there.

In case of any troubles please raise a new issue with the exact commands and steps that can demonstrate the failure.

Private, high-priority commercial support is available from: https://xpbrew.consulting/

/cc @dlowder-salesforce

**Comment by dlowder-salesforce** [comment]
Just tested with react-native-tvos@0.61.2-0 and things seem to work well, once the example Podfile was updated for RN 0.61.

**Comment by brodybits** [comment]
> [...] once the example Podfile was updated for RN 0.61.

Thanks for the update. Would you mind sharing any pointers for TV amateurs such as myself?

**Comment by dlowder-salesforce** [comment]
Sure!  I used create-react-native-module 0.11.1 as follows:

```
create-react-native-module test-module --author-name "Douglas Lowder" --author-email "dlowder@salesforce.com" --license MIT --view --use-cocoapods --generate-example --example-name moduleExample --example-react-native-version react-native@npm:react-native-tvos@0.61.2-0
```

Then I copied in the Podfile from the react-native-tvos template folder (https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.61.2/template/ios/Podfile) to the example project ios directory, modifying the target names in the Podfile to match the example project.

**Comment by brodybits** [comment]
> Then I copied in the Podfile from the react-native-tvos template folder (https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.61.2/template/ios/Podfile) to the example project ios directory

Interesting, thanks. This sounds like something that should be done by react-native-cli itself, right?

Can you think of anything else that I or we may be missing here?

**Comment by dlowder-salesforce** [comment]
Not at the moment... the Podfile is the only issue I hit.  I can take a look at how it's generated -- seems like it should be coming from the template directory in whatever RN version is chosen for the example....
