### ISSUE TITLE
cleanup lib & utils, etc.

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#15]
I suspect most of the sources in `utils` could be replaced by existing npm packages. Maybe a limited number of new utility packages to replace the rest.

related to: #14 - move some JavaScript files into `lib` subdirectory

P.S. My goal is to get rid of the `utils` subdirectory, if possible.

**Comment by brodybits** [comment]
Here are my findings from a quick look through what is now in `lib/utils`:

- use the Promise-based interface of [`fs-extra`](https://www.npmjs.com/package/fs-extra) calls instead of `createFile.js` & `createFolder.js`
- replace implementation in `exec.js` with use of [`execa`](https://www.npmjs.com/package/execa) package; also replace use of any `child_process` calls with [`execa`](https://www.npmjs.com/package/execa)  calls in `lib.js`
- I think that `hasPrefix.js` and `isUpperCase.js` can go away
- implementation in `npmAddScriptSync.js` which updates `scripts` in `package.json` can be replaced by using one of the following utilities:
  - [`jsonfile`](https://www.npmjs.com/package/jsonfile)
  - [`edit-json-file`](https://www.npmjs.com/package/edit-json-file)

Synchronous file & process exec calls should be avoid whenever possible.

I think it would be ideal to use await and async instead of Promise chains (#39).

**Comment by dsyne** [comment]
Hey sorry, been a bit busy but am looking at this now, have removed most of the utils. Am currently removing promises for async/await

**Comment by brodybits** [comment]
Thanks @dsyne for your work so far on this, no rush on my part.

I already saw your [`remove-utils`](https://github.com/dsyne/create-react-native-module/tree/remove-utils) branch, and I used the first couple changes in WIP PR #52 to start adding automatic testing (#40). I have also factored out `lib/utils/exec.js` in the same PR, now with a mockable API that I can use for automatic testing.

I would actually like to hold off on changes such as integrating `execa` and using await & async until the automatic testing is ready and integrated. I will also take a look into mocking and testing the of the example package JSON functionality.

I will likely hide some of our conversation in #28 as resolved.

**Comment by dsyne** [comment]
Ok, no worries. Shall u park the rest of the work on that branch for now then? I'm happy to pick up another issue, maybe #37  and #5 unless anything else is more pressing

**Comment by brodybits** [comment]
Hi @dsyne, I just updated the title to hopefully match of the scope of our ongoing discussion. My response should be coming with some ideas in the next 6-12 hours or so. Thanks for your help so far.

**Comment by brodybits** [comment]
My apologies for the delay, I am still in the middle of a few things so you may as well park the work for now. I hope to send my response soon. Proposals are always welcome but beware that I will likely make some major changes to the JavaScript in the next 1-2 days or so.

**Comment by dsyne** [comment]
No problem at all, i've been away for a few days and am just catching up with things at work. I'll happily jump back on when you have things sorted so i'll keep an eye out. 👌

**Comment by brodybits** [comment]
FYI you will likely see some more updates before you see my response. I hope to finish these soon, no promises yet. Another thing is that I may start to use this package to promote some of my services. I may consider promoting other people in the future, no promises though.

In general, critical feedback on PRs and other proposed ideas would always be helpful. Also for draft and WIP PRs.

**Comment by brodybits** [comment]
Remaining artifact was factored out of `lib/utils` so this task should be finished now.

Thanks @dsyne for your offers to help. As I tried to explain before, your input and contributions would be appreciated anytime.
