### ISSUE TITLE
Automate full mutation report on Stryker dashboard

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#190]
Full mutation report on the Stryker dashboard seem to be supported but yet (fully) documented:

- stryker-mutator/stryker#1791
- stryker-mutator/stryker-handbook#27
- stryker-mutator/stryker#1783

**Comment by nicojs** [comment]
Cool @brodybits , you're one alert guy 🐶

I will update here once we're up and running

**Comment by brodybits** [comment]
Thanks @nicojs, looking forward to it.

**Comment by brodybits** [comment]
I finally got this project working on the dashboard, automated in GitHub actions in PR #321, and added to the badges. The "robobar" example is really helpful for API beginners like myself. Woot!
