### ISSUE TITLE
What is the recommended RN version? 0.59 and below or 0.60+?

### ISSUE THREAD

**Issue by Ashish-Nanda** [brodybits/create-react-native-module#192]
Hi,
The README file seems to be updated to say: 
React Native versions supported:
recommended: 0.61, 0.60 (see known quirks and issues below)
outdated: 0.59

However when I create a new library with the latest version of the `create-react-native-module` it seems to still be 0.59.10. Also I assume the generated example is also 0.59. It fails to generate it for me since I use `npx react-native` instead of the global CLI. 

Any information clarifying the above would be great. Thank you.

**Comment by barrylachapelle** [comment]
+1

**Comment by PomegranateApps** [comment]
I am having the same problem. It doesn't create the example folder or pod file for iOS. Are there updated instructions?

**Comment by brodybits** [comment]
This is already tracked in #93 to fix React Native 0.61 support.

**Comment by brodybits** [comment]
I just published version 0.14.0. The generated example is now for React Native 0.61. React Native 0.59 is no longer supported by this utility.
