### ISSUE TITLE
Exporting JS methods in index.js

### ISSUE THREAD

**Issue by kitty7756** [brodybits/create-react-native-module#20]
Thanks for this! Really helpful to get started on creating native modules for react native projects.
I'm currently creating a library for react native and I was wondering if it's possible to write my own JS wrapper (possibly in index.js) and export those instead of exporting native modules? I was trying to write a dummy method but seems like I couldn't get export of that to work

**Comment by brodybits** [comment]
Yes it should be possible to export your own JavaScript wrapper object around the original object from `NativeModules`.

My one advice would be to design the native module API to strive for a minimal amount of JavaScript that is in the native module, with a larger wrapper object or wrapper object factory in one or more separate JavaScript module.

In case of continued issues with the JavaScript wrapper object, I would recommend that you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by brodybits** [comment]
Closing for now. In case you have further questions or can produce a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please do not hesitate to post here are in a new issue.
