### ISSUE TITLE
Using @react-native-community/cli instead of react-native-cli

### ISSUE THREAD

**Issue by zhigang1992** [brodybits/create-react-native-module#204]
@react-native-community/cli 

is the official next version of `react-native-cli`

https://github.com/react-native-community/cli

There are some differences with them.

**Comment by brodybits** [comment]
Definitely an interesting idea.

From https://github.com/react-native-community/cli#using-npx-recommended and https://github.com/facebook/react-native/blob/0.61-stable/package.json#L4 I start to wonder why not just use cli.js from the `react-native` package itself?

**Comment by zhigang1992** [comment]
Yeah, it'd be awesome if we can eliminate this external dependency, and don't have to worry about them getting out of sync.

**Comment by brodybits** [comment]
I just tried this idea, encountered this issue: <https://github.com/facebook/metro/issues/1> (see also <https://github.com/facebook/metro/issues/286>)

Following from <https://github.com/facebook/metro/issues/286#issuecomment-490458858> and <https://github.com/facebook/metro/issues/1#issuecomment-421628147>, I thought to try adding the following entry to the end of the `module.exports` object in `example/metro.config.js`:

```js
watchFolders: ['.', '../']
```

Worked like a charm. Maybe I should use `path.resolve` as discussed in <https://github.com/facebook/metro/issues/1#issuecomment-541642857>.

**Comment by brodybits** [comment]
This issue is now pinned in first place, I hope to get it resolved in the near future. And I would definitely favor this idea over using npx as proposed in PR #267.

**Comment by brodybits** [comment]
I would like to clarify for the sake of some others that this project would use `@react-native-community/cli` by adding it to its package dependencies, as they documented here: https://github.com/react-native-community/cli#about

**Comment by brodybits** [comment]
The one major drawback of this idea is that `@react-native-community/cli` seemed to be a heavy dependency when I tried adding it in my workarea. I think the ideal solution would be to somehow render the example from the template in `react-native` itself and then use Yarn and `pod` to install its dependencies.

Any alternatives from the user community would be welcome for discussion.
