### ISSUE TITLE
How to update/reinstall the package?

### ISSUE THREAD

**Issue by codestergit** [brodybits/create-react-native-module#208]
I created the project with

> create-react-native-module mylibrary --generate-example

After creating project I made changes to mylibrary. 
But runing
``yarn install`` and  ``yarn add`` in my example project do not update the mylibrary dependency for iOS in Xcode. It takes old module initially created.

**Comment by brodybits** [comment]
In that case I would recommend you remove node_modules and try it again.

I would need a minimal, reproducible example to consider this a bug: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by maitrungduc1410** [comment]
Hi @brodybits , so everytime I change my native code I need to re-install the package to make example project working, right?
