### ISSUE TITLE
No Podfile found in project directory

### ISSUE THREAD

**Issue by HumanUndead** [brodybits/create-react-native-module#218]
I created a new module, first it got created with version 0.59 not 0.61+

also when I try cd iOS then pod install, it says 
[!] No `Podfile' found in the project directory.

do we have to manually create the pod file? and if yes what is the minimal Podfile contents.

**Comment by brodybits** [comment]
There is an option you can use to generate example with React Native 0.61. I think pod install is not supported for React Native 0.59.

**Comment by brodybits** [comment]
I have updated this utility to work with React Native 0.61, closing now. In case of any further issues a new issue would be much appreciated.
