### ISSUE TITLE
Import dynamic framework doesn't work

### ISSUE THREAD

**Issue by mateioprea** [brodybits/create-react-native-module#229]
Hello, 

I'm trying to import a dynamic library into a module that I'm building. The module will be written in swift. 

I've added the .framework file, changed the Header search paths to $(SRCROOT)/../../ios/. 

Installation in a React Native app is successful but I get: 

'Library_Name/Library_Name.h' file not found in the Bridging header file. 

If I build the native module only, everything is successful.

**Comment by brodybits** [comment]
Swift is currently not supported, discussed in other issues.

**Comment by mateioprea** [comment]
@brodybits i managed to do it, actually. :)

**Comment by brodybits** [comment]
It would help others if you would not mind sharing your solution in #221, thanks!
