### ISSUE TITLE
Use symbol link for example

### ISSUE THREAD

**Issue by sunnylqm** [brodybits/create-react-native-module#232]
There is some [workaround](https://github.com/sunnylqm/react-native-geckoview/blob/master/example/metro.config.js) to let metro bundler support [symbol link](https://github.com/sunnylqm/react-native-geckoview/blob/master/example/package.json#L15), so that we can `directly` modify the library code and test them in the example project .

**Comment by brodybits** [comment]
Thanks @sunnylqm for both the suggestion and the information. I will likely need some time to investigate.

**Comment by brodybits** [comment]
I tried this in my work area, seems to work if I would add the following entry to the end of the `module.exports` object in `example/metro.config.js` (thanks to  <https://github.com/facebook/metro/issues/286#issuecomment-490458858> and <https://github.com/facebook/metro/issues/1#issuecomment-421628147> for pointers to the general idea):

```js
watchFolders: ['.', '../']
```
(Maybe I should `path.resolve` as discussed in <https://github.com/facebook/metro/issues/1#issuecomment-541642857>.)

**Comment by brodybits** [comment]
I just published [`react-native-module-init`](https://www.npmjs.com/package/react-native-module-init) which both offers an interactive CLI and uses a symbolic link in the generated example.

**Comment by brodybits** [comment]
> [...]
> ```js
> watchFolders: ['.', '../']
> ```

Adding `watchFolders: ['.', '../']` seems to be enough to work on React Native 0.60; additional resolver.extraNodeModules entry like @sunnylqm has in [workaround metro.config.js](https://github.com/sunnylqm/react-native-geckoview/blob/master/example/metro.config.js) linked from the description seems to be needed as well on React Native 0.61 & 0.62.

The following `resolver` entry seems to work for me on React Native 0.61 & 0.62:

```js
  resolver: {
    extraNodeModules: new Proxy(
      {},
      { get: (_, name) => path.resolve('.', 'node_modules', name) }
    )
  }
```

I think @johnryan deserves credit for the pointers to both workarounds in <https://github.com/facebook/metro/issues/1#issuecomment-541642857>.

I am working on a new PR with this functionality, which should be ready within the next couple of days or so.

**Comment by wassil** [comment]
With `watchFolders: ['.', '../']` watchman complains that `unable to resolve root .: path "." must be absolute`

I ended up using `watchFolders: [path.resolve(__dirname), path.resolve(__dirname) + '/../']`

**Comment by YOEL311** [comment]
hey @brodybits 
Thanks to your library

I need to use it but my example app is not inside the folder of the library, 
is exist beside the app like this structure

mono-repo folder
   -- example-app
     -- my-library
   
  in my example app, I tried to link to my library but I got an error
  
  
  in my ``package.json`` file of the App 
  
````
  "dependencies": {
    "my-library": "link:../my-library",
  ````
  I see in my ``node-modules`` is like the folder but when I start the app with

`` npx react-native start --reset-cache``
  
  I got error
  
```
Watchman `watch-project` finished after 16.0s.
Waiting for Watchman `query` (10s).
```
  how I can to fix it to work with my module with ``react-native`` metro bundle
