### ISSUE TITLE
Create examples with `npx` instead of globally installed `react-native-cli`

### ISSUE THREAD

**Issue by arniu** [brodybits/create-react-native-module#265]
According to [react-native-community/cli](https://github.com/react-native-community/cli#using-npx-recommended):

> 
> ## Using npx (recommended)
> > Available since react-native@0.60
>
> This method is preferred if you don't want to install global packages.
> 
> ```
> npx react-native init MyApp
> ```

**Comment by brodybits** [comment]
Thanks for the proposal. I generally do not like waiting for npx to download each tool every time I want to run it, and I would still count running npx as use of an external tool.

I am thinking that using `@react-native-community/cli` as discussed in #204, or even using `cli.js` from `react-native` itself as I said in <https://github.com/brodybits/create-react-native-module/issues/204#issuecomment-560992890>, would be a better solution. I just pinned #204 in first place, to hopefully get it resolved in the near future, closing this one for now.

**Comment by arniu** [comment]
Yes, npx will download the tool, and then cache it.

So for the people who use it again and again, they will not wait any more.
For the people who use it only once, downloading is inevitable. By npx, or by hand, downloading always go.

Moreover, npx will be the best solution for the ones who have no permission to install global packages.

**Comment by arniu** [comment]
As for `@react-native-community/cli`, it is not intended to install globally.

**Comment by brodybits** [comment]
@arniu that is all correct. I still really do not like the idea of any tools like this one suddenly installing its dependencies via `npx`. The idea discussed in #204 would be to add `@react-native-community/cli` as a package dependency. But I am still open to discuss alternatives and ideas that users may have. Thanks.
