### ISSUE TITLE
How to integrate aar library to native module?

### ISSUE THREAD

**Issue by antoniosk10** [brodybits/create-react-native-module#475]
Hi. I need to integrate aar library to my native module. So, I created structure of the package by `create-react-native-module`, then I created new folder `libs` and added `implementation fileTree(dir: "libs", include: ["*.aar"])` to `build.gradle` in my package

![Screenshot at Jan 31 16-42-05](https://user-images.githubusercontent.com/49447404/151804199-de73272d-fe25-434d-bd66-c5a537b78ae3.png)

Then I import my class from my aar into my module. And it works fine. Build without errors:

![Screenshot at Jan 31 16-43-30](https://user-images.githubusercontent.com/49447404/151804385-310a0cc0-7b7e-4346-8631-0781cb352e90.png)

But when I import this class in `MainApplication.java` of the test app I get an error: 
![Screenshot at Jan 31 16-47-26](https://user-images.githubusercontent.com/49447404/151805041-778003a1-a8a4-4251-bc0d-d1b9c95fb94d.png)
![Screenshot at Jan 31 16-50-38](https://user-images.githubusercontent.com/49447404/151805482-13f00fa5-4e42-4feb-8a83-b20e38a6cde3.png)

What I missed?
Help me please! Thanks.

**Comment by vokhuyetOz** [comment]
you can check your lib packageId, make sure it right

**Comment by antoniosk10** [comment]
I figured out. Replaced ` implementation fileTree(dir: 'libs', include: ['*.aar'])` with ` api fileTree(dir: 'libs', include: ['*.aar'])`
