### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by RWOverdijk** [brodybits/create-react-native-module#90]
I just now created a project, configured (signing) teams for the example and tried running it. It's giving me:

> error: 'glog/logging.h' file not found

**Comment by brodybits** [comment]
Please show the following:

* https://stackoverflow.com/help/minimal-reproducible-example
* which React Native version
* which platform
* what command you used to start the build, if you used the command line

**Comment by RWOverdijk** [comment]
I'm not doing that. This was on master, the command I used was:

`create-react-native-module beaconRadar --package-identifier=studio.spoonx --github-account=SpoonX --author-name=RWOverdijk --author-email=wesley@spoonx.studio --generate-example`

I'll close this issue because I created my own module (which is also why I can't put time into reproducing the issue right now).
